# FILE: .github/actions/build-qt-macos/action.yml

name: "Prepare a static build of Qt 6 (macOS)"
description: "Automates building static Qt 6 from source on macOS."

inputs:
  version:
    type: string
    description: "The version of Qt, e.g. 6.8.0"
    required: true
  dir:
    type: string
    description: "The directory where Qt should be installed"
    required: true
  submodules:
    type: string
    description: "Comma separated list of Qt modules"
    required: true
  
outputs:
  dir:
    description: "The Qt installation directory"
    value: ${{ inputs.dir }}

runs:
  using: "composite"
  steps:
    - name: Set QT_INSTALL_DIR
      id: set-qt-dir
      shell: bash
      run: echo "qt-install-dir=${{ inputs.dir }}" >> $GITHUB_OUTPUT

    - name: Cache Qt (macOS)
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
        key: qt-static-macos-${{ inputs.version }}-modules-${{ inputs.submodules }}-v1

    - name: Install Dependencies (macOS)
      if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
      shell: bash
      run: brew install ninja

    - name: Build static Qt 6 from source (macOS)
      if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        set -ex
        QT_SRC_DIR=${{ steps.set-qt-dir.outputs.qt-install-dir }}/src
        QT_BUILD_DIR=${{ steps.set-qt-dir.outputs.qt-install-dir }}/build
        
        mkdir -p $QT_SRC_DIR
        cd $QT_SRC_DIR
        
        git clone --depth 1 --branch "v${{ inputs.version }}" https://code.qt.io/qt/qt5.git
        cd qt5
        
        perl init-repository --module-subset "${{ inputs.submodules }}" -f
        
        mkdir -p $QT_BUILD_DIR
        cd $QT_BUILD_DIR
        
        ../src/qt5/configure -prefix "${{ steps.set-qt-dir.outputs.qt-install-dir }}" \
          -release -static -opensource -confirm-license \
          -no-dbus -no-pch -nomake examples -nomake tests \
          -skip qtwebengine -skip qtdeclarative -skip qttools
          
        cmake --build . --parallel $(sysctl -n hw.ncpu)
        cmake --install .
