name: "Build Engine"
description: "Builds C++ Engine with Qt (Full Logic)"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    # --- LINUX DEPENDENCIES ---
    - name: Install base dependencies (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake qt6-base-dev zip apt-file pkg-config
        sudo apt-file update

    - name: Install Complex XCB Deps (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        PKGFILE=packages/engine/PKGBUILD
        if [ ! -f "$PKGFILE" ]; then echo "PKGBUILD missing"; exit 1; fi
        mapfile -t XCB_LIBS < <(awk '/^XCB_LIB_BASENAMES/ {in=1; next} in && /^\)/ {exit} in {gsub(/["]/,""); print}' "$PKGFILE" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | tr -d '\n')
        if [ "${#XCB_LIBS[@]}" -eq 1 ]; then read -r -a XCB_LIBS <<< "${XCB_LIBS[0]}"; fi
        for lib in "${XCB_LIBS[@]}"; do
          lib=$(echo "$lib" | tr -d '[:space:]'); if [ -z "$lib" ]; then continue; fi
          pkgs=$(apt-file search --regexp "/${lib}$" 2>/dev/null | cut -d: -f1 | sort -u)
          if [ -n "$pkgs" ]; then sudo apt-get install -y --no-install-recommends $pkgs || true; fi
        done

    # --- WINDOWS DEPENDENCIES ---
    - name: Install Prereqs (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        winget install --id Kitware.CMake --silent --accept-package-agreements --accept-source-agreements
        winget install --id Ninja-build.Ninja --silent --accept-package-agreements --accept-source-agreements
        if (-not (Get-Command cmake -ErrorAction SilentlyContinue)) { exit 1 }
        if (-not (Get-Command ninja -ErrorAction SilentlyContinue)) { exit 1 }

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # --- MAC DEPENDENCIES ---
    - name: Install Prereqs (Mac)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew update
        brew install cmake qt
        echo "QT_PATH=$(brew --prefix qt)" >> $GITHUB_ENV
        echo "$(brew --prefix qt)/bin" >> $GITHUB_PATH

    # --- BUILD ---
    - name: Run Build (Non-Windows)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: packages/engine
      run: chmod +x PKGBUILD && ./PKGBUILD

    - name: Run Build (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: packages/engine
      run: |
        .\PKGBUILD.ps1
        if (-not (Test-Path "dist\drawview.exe")) { exit 1 }

    # --- ZIP OUTPUT ---
    - name: Zip Artifacts
      shell: bash
      run: |
        DIST_ROOT="$GITHUB_WORKSPACE/dist-out"
        mkdir -p "$DIST_ROOT"

        if [ "$RUNNER_OS" == "Windows" ]; then
          ZIP_NAME="engine-win-x64.zip"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ZIP_NAME="engine-mac-x64.zip"
        else
          ZIP_NAME="engine-linux-x64.zip"
        fi

        ZIP_FULL_PATH="$DIST_ROOT/$ZIP_NAME"
        echo "Zipping Engine to $ZIP_FULL_PATH"

        cd packages/engine/dist

        if [ "$RUNNER_OS" == "Windows" ]; then
          7z a -tzip -r "$ZIP_FULL_PATH" .
        else
          zip -r "$ZIP_FULL_PATH" .
        fi
