name: "Build Setup Wizard"
description: "Builds Tauri Setup Wizard"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "npm"
        cache-dependency-path: "packages/setup/package-lock.json"

    - name: Install Frontend Dependencies
      shell: bash
      working-directory: packages/setup
      run: npm ci

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.1-dev \
          build-essential \
          curl \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

    - name: Build Tauri App
      shell: bash
      working-directory: packages/setup
      run: npm run tauri build

    - name: Prepare Artifacts
      shell: bash
      working-directory: packages/setup/src-tauri
      run: |
        # Use absolute path to workspace root for reliability
        DIST_DIR="${{ github.workspace }}/dist-out"
        mkdir -p "$DIST_DIR"
        
        if [ "$RUNNER_OS" == "Windows" ]; then
          OS_TAG="win"
          # Placeholder
        elif [ "$RUNNER_OS" == "Linux" ]; then
          OS_TAG="linux"
          
          # Verify binary exists
          BIN_PATH="target/release/spatialshot-setup"
          [ -f "target/release/spatialshot-setup-wizard" ] && BIN_PATH="target/release/spatialshot-setup-wizard"
          
          if [ ! -f "$BIN_PATH" ]; then
            echo "::error::Binary not found at $BIN_PATH"
            exit 1
          fi
          
          ZIP_NAME="spatialshot-setup-${OS_TAG}-x64.zip"
          zip -j "$DIST_DIR/$ZIP_NAME" "$BIN_PATH"

        elif [ "$RUNNER_OS" == "macOS" ]; then
          OS_TAG="mac"
          ARCH="x64"
          [[ $(uname -m) == 'arm64' ]] && ARCH="arm64"
          
          APP_DIR="target/release/bundle/macos"
          APP_NAME="spatialshot-setup-wizard.app"
          ZIP_NAME="spatialshot-setup-${OS_TAG}-${ARCH}.zip"
          
          if [ -d "$APP_DIR/$APP_NAME" ]; then
            pushd "$APP_DIR"
            # Zip into the absolute dist dir
            zip -r "$DIST_DIR/$ZIP_NAME" "$APP_NAME"
            popd
          else
             echo "::error::App bundle not found at $APP_DIR/$APP_NAME"
             exit 1
          fi
        fi
        
        echo "Contents of $DIST_DIR:"
        ls -l "$DIST_DIR"