name: "Build Orchestrator"
description: "Builds Rust Orchestrator for specific OS"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- LINUX SETUP ---
    - name: Install MUSL (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools musl-dev libudev-dev libdbus-1-dev
        rustup target add x86_64-unknown-linux-musl

    # --- BUILD ---
    - name: Build
      working-directory: ./packages/orchestrator
      shell: bash
      run: |
        cargo update
        if [ "$RUNNER_OS" == "Linux" ]; then
           cargo build --release --target x86_64-unknown-linux-musl
        else
           cargo build --release
        fi

    # --- ZIP OUTPUT ---
    - name: Zip Artifacts
      shell: bash
      run: |
        mkdir -p dist-out

        if [ "$RUNNER_OS" == "Windows" ]; then
          ZIP_NAME="orchestrator-win-x64.zip"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          ZIP_NAME="orchestrator-mac-x64.zip"
        else
          ZIP_NAME="orchestrator-linux-x64.zip"
        fi

        BIN_PATH=$(find packages/orchestrator/target -type f -name "spatialshot-orchestrator*" | grep release | grep -v "\.d" | head -n 1)

        echo "Zipping $BIN_PATH to $ZIP_NAME..."

        if [ "$RUNNER_OS" == "Windows" ]; then
          mkdir temp_zip
          cp "$BIN_PATH" temp_zip/
          cd temp_zip
          7z a -tzip "../dist-out/$ZIP_NAME" .
        else
          zip -j "dist-out/$ZIP_NAME" "$BIN_PATH"
        fi
