name: Build Static ycaptool

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-static:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build using Docker for static linking
      run: |
        docker run --rm -v $(pwd):/build ubuntu:22.04 bash -c "
          set -ex
          apt-get update
          apt-get install -y build-essential cmake ninja-build git
          
          # Install Qt6 from source with static linking
          cd /tmp
          apt-get install -y wget xz-utils
          wget https://download.qt.io/official_releases/qt/6.8/6.8.0/single/qt-everywhere-src-6.8.0.tar.xz
          tar xf qt-everywhere-src-6.8.0.tar.xz
          cd qt-everywhere-src-6.8.0
          
          # Install Qt build dependencies
          apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev \
            libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libfreetype6-dev libpng-dev \
            libjpeg-dev libglib2.0-dev libdbus-1-dev
            
          ./configure -prefix /opt/qt6-static -static -release -opensource -confirm-license \
            -nomake examples -nomake tests -skip webengine -skip qtmultimedia \
            -feature-dbus -qt-zlib -qt-libpng -qt-libjpeg -qt-freetype -qt-pcre
          
          make -j$(nproc)
          make install
          
          # Build ycaptool
          cd /build/packages/ycaptool
          /opt/qt6-static/bin/qmake ycaptool.pro
          make -j$(nproc)
          
          # Verify static binary
          file ycaptool
          ldd ycaptool 2>/dev/null | grep -q 'not a dynamic executable' && echo '✅ Static binary created' || echo '❌ Not a static binary'
        "

    - name: Extract built binary from Docker
      run: |
        # The binary should be in packages/ycaptool/ycaptool after Docker run
        if [ -f "packages/ycaptool/ycaptool" ]; then
          echo "✅ Static ycaptool built successfully"
          file packages/ycaptool/ycaptool
        else
          echo "❌ Build failed - binary not found"
          exit 1
        fi

    - name: Upload static binary
      uses: actions/upload-artifact@v4
      with:
        name: ycaptool-static-linux
        path: packages/ycaptool/ycaptool
        retention-days: 30