name: Build ycaptool (Linux)

on:
  # push:
  workflow_dispatch:

jobs:
  build-qt-static:
    runs-on: ubuntu-latest
    env:
      QT_VERSION: 6.8.0
    outputs:
      qt-install-dir: ${{ steps.set-qt-dir.outputs.qt-install-dir }}

    steps:
      - uses: actions/checkout@v4

      - name: Set QT_INSTALL_DIR
        id: set-qt-dir
        run: echo "qt-install-dir=${{ runner.temp }}/qt-static" >> $GITHUB_OUTPUT

      - name: Cache Qt (restore/save)
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
          key: qt-static-linux-${{ env.QT_VERSION }}-${{ runner.os }}-${{ hashFiles('.github/actions/build-qt-static/action.yml') }}-v4
          restore-keys: |
            qt-static-linux-${{ env.QT_VERSION }}-${{ runner.os }}-

      - name: Build static Qt
        if: ${{ steps.cache-qt.outputs.cache-hit != 'true' }}
        uses: ./.github/actions/build-qt-static
        with:
          version: ${{ env.QT_VERSION }}
          configure-args: "-opensource -confirm-license -no-pch -skip qtwebengine -nomake tests -nomake examples"
          dir: ${{ steps.set-qt-dir.outputs.qt-install-dir }}
          submodules: "qtbase,qtshadertools,qtdeclarative,qttools,qtwayland"

      - name: Upload Qt install artifact (for transfer to next job)
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: qt-install
          path: ${{ steps.set-qt-dir.outputs.qt-install-dir }}

  build-ycaptool:
    needs: build-qt-static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Qt install artifact
        uses: actions/download-artifact@v4
        with:
          name: qt-install
          path: ${{ needs.build-qt-static.outputs.qt-install-dir }}

      - name: Install additional dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl python3 cmake ninja-build git \
            libgl1-mesa-dev libfontconfig1-dev libfreetype6-dev \
            libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev \
            libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev \
            libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev \
            libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev \
            libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libatspi2.0-dev dbus-x11 \
            libpcre2-dev libdbus-1-dev libpng-dev libjpeg-dev libglib2.0-dev \
            python3 gperf bison flex libwayland-dev
        shell: bash

      - name: Build ycaptool
        env:
          QT_INSTALL_DIR: ${{ needs.build-qt-static.outputs.qt-install-dir }}
        run: |
          export PATH="${{ env.QT_INSTALL_DIR }}/bin:$PATH"
          export PKG_CONFIG_PATH="${{ env.QT_INSTALL_DIR }}/lib/pkgconfig:$PKG_CONFIG_PATH"
          
          echo "Setting execute permissions for Qt binaries..."
          chmod -R +x ${QT_INSTALL_DIR}/bin
          chmod -R +x ${QT_INSTALL_DIR}/libexec
          cd packages/ycaptool
          
          qmake CONFIG+=static ycaptool.pro
          
          make -j$(nproc)
          mkdir -p dist
          cp ycaptool dist/
          
          echo "Stripping binary..."
          strip dist/ycaptool
          
          rm ycaptool
        shell: bash

      - name: Verify static linking (check that Qt is not dynamic)
        run: |
          # This test checks that the executable is NOT linked to any libQt*.so files.
          ldd packages/ycaptool/dist/ycaptool | grep libQt && (echo "Error: ycaptool is dynamically linked to Qt"; exit 1) || echo "Success: ycaptool is statically linked to Qt"
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ycaptool-linux
          path: packages/ycaptool/dist/ycaptool
